services:
  server:
    image: svalasovich/server:latest
    ports:
      - "9000:9000"
  client:
    image: svalasovich/client:latest
    environment:
      TCP__ADDRESS: "server:9000"
      INTERVAL: "1s"
    depends_on:
      - server