---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: chore(github)

  - package-ecosystem: docker
    directory: /build/
    schedule:
      interval: monthly
    commit-message:
      prefix: chore(docker)

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: chore(go)
